### ISSUE TITLE
Android build error in PasswordCredentialPlugin.kt

### ISSUE THREAD

**Issue by sachavieuxroy** [irgaly/flutter_password_credential#3]
Launching lib\main.dart on SM N976N in debug mode...
Running Gradle task 'assembleDebug'...
C:\src\flutter\.pub-cache\git\flutter_password_credential-34baa01848a9c2a0b3ffe7fc980b079219ac2bb3\android\src\main\kotlin\net\irgaly\password_credential\PasswordCredentialPlugin.kt:79:6: error: 'OptIn' is only available since Kotlin 1.3.70 and cannot be used in Kotlin 1.3
    @OptIn(UnstableDefault::class)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':password_credential:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 2s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by irgaly** [comment]
related #4
