### ISSUE TITLE
Android build error in PasswordCredentialPlugin.kt & Mediation.kt

### ISSUE THREAD

**Issue by sachavieuxroy** [irgaly/flutter_password_credential#4]
Launching lib\main.dart on SM N976N in debug mode...
Running Gradle task 'assembleDebug'...
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.1\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java:71: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.1\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java:189: warning: [deprecation] setDataCollectionDefaultEnabled(boolean) in FirebaseApp has been deprecated
          firebaseApp.setDataCollectionDefaultEnabled(enabled);
                     ^
2 warnings
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.1\android\src\main\java\io\flutter\plugins\firebase\firestore\FlutterFirebaseFirestorePlugin.java:103: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.1\android\src\main\java\io\flutter\plugins\firebase\firestore\streamhandler\TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.3.0\android\src\main\java\io\flutter\plugins\firebase\auth\FlutterFirebaseAuthPlugin.java:80: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
1 warning
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.1.1\android\src\main\java\io\flutter\plugins\firebase\storage\FlutterFirebaseStoragePlugin.java:38: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
1 warning
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\password_credential-0.2.0\android\src\main\kotlin\net\irgaly\password_credential\PasswordCredentialPlugin.kt:79:6: error: 'OptIn' is only available since Kotlin 1.3.70 and cannot be used in Kotlin 1.3
    @OptIn(UnstableDefault::class)
     ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\password_credential-0.2.0\android\src\main\kotlin\net\irgaly\password_credential\entity\Mediation.kt:5:1: error: @Serializable annotation is ignored because it is impossible to serialize automatically interfaces or enums. Provide serializer manually via e.g. companion object
@Serializable
^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':password_credential:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by irgaly** [comment]
sorry, I'll fix it soon.

**Comment by irgaly** [comment]
@sachavieuxroy
I have published v0.3.1.
You should use Kotlin 1.5.10 for this plugin.
